name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install packages to build
      run: |
        sudo apt-get install -y libx11-dev pkg-config libharfbuzz-dev libfontconfig-dev libxft-dev build-essential
    - name: make
      run: make
    - name: make archive
      run: make archive
